### ISSUE TITLE
ScrAPD fails when no data is retrieved

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#83]
Issue Type
----------

- Bug report

Current Behavior
----------------

Sometimes, the requests fail and no data gets retrieved:

```bash
++ scrapd -v --format json --from 'Jan 1 2019' --to 'Dec 31 2019'
Fetching page 1...
aiohttp exception for http://austintexas.gov/department/news/296 -> None
expected string or bytes-like object
Traceback (most recent call last):

  File "/home/circleci/project/venv/bin/scrapd", line 10, in <module>
    sys.exit(cli())
    │   │    └ <click.core.Command object at 0x7f96aac9aa90>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/circleci/project/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <bound method BaseCommand.main of <click.core.Command object at 0x7f96aac9aa90>>
           └ <click.core.Command object at 0x7f96aac9aa90>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f96aac9a470>
         │    └ <bound method Command.invoke of <click.core.Command object at 0x7f96aac9aa90>>
         └ <click.core.Command object at 0x7f96aac9aa90>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'verbose': 1, 'format_': 'json', 'from_': 'Jan 1 2019', 'to': 'Dec 31 2019', 'gcontributors': None, 'gcredentials': None, 'page...
           │   │      │    │           └ <click.core.Context object at 0x7f96aac9a470>
           │   │      │    └ <function cli at 0x7f96a6243b70>
           │   │      └ <click.core.Command object at 0x7f96aac9aa90>
           │   └ <bound method Context.invoke of <click.core.Context object at 0x7f96aac9a470>>
           └ <click.core.Context object at 0x7f96aac9a470>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'verbose': 1, 'format_': 'json', 'from_': 'Jan 1 2019', 'to': 'Dec 31 2019', 'gcontributors': None, 'gcredentials': None, 'page...
           │         └ ()
           └ <function cli at 0x7f96a6243b70>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
           │ │                       │       └ {'verbose': 1, 'format_': 'json', 'from_': 'Jan 1 2019', 'to': 'Dec 31 2019', 'gcontributors': None, 'gcredentials': None, 'page...
           │ │                       └ ()
           │ └ <function get_current_context at 0x7f96adaa8268>
           └ <function cli at 0x7f96a6243ae8>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/scrapd/cli/cli.py", line 76, in cli
    command.execute()
    │       └ <bound method AbstractCommand.execute of <scrapd.cli.cli.Retrieve object at 0x7f96aad06908>>
    └ <scrapd.cli.cli.Retrieve object at 0x7f96aad06908>
> File "/home/circleci/project/venv/lib/python3.7/site-packages/scrapd/cli/base.py", line 34, in execute
    sys.exit(self._execute())
    │   │    │    └ <bound method Retrieve._execute of <scrapd.cli.cli.Retrieve object at 0x7f96aad06908>>
    │   │    └ <scrapd.cli.cli.Retrieve object at 0x7f96aad06908>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/scrapd/cli/cli.py", line 91, in _execute
    self.args['to'],
    │    └ {'verbose': 1, 'format_': 'json', 'from_': 'Jan 1 2019', 'to': 'Dec 31 2019', 'gcontributors': None, 'gcredentials': None, 'page...
    └ <scrapd.cli.cli.Retrieve object at 0x7f96aad06908>
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object async_retrieve at 0x7f96a62381c8>
           │    └ <bound method BaseEventLoop.run_until_complete of <_UnixSelectorEventLoop running=False closed=True debug=False>>
           └ <_UnixSelectorEventLoop running=False closed=True debug=False>
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
           │      └ <built-in method result of _asyncio.Task object at 0x7f96a6242188>
           └ <Task finished coro=<async_retrieve() done, defined at /home/circleci/project/venv/lib/python3.7/site-packages/scrapd/core/apd.p...
  File "/home/circleci/project/venv/lib/python3.7/site-packages/scrapd/core/apd.py", line 442, in async_retrieve
    page_details_links = extract_traffic_fatalities_page_details_link(news_page)
                         │                                            └ None
                         └ <function extract_traffic_fatalities_page_details_link at 0x7f96a7966d08>
  File "/home/circleci/project/venv/lib/python3.7/site-packages/scrapd/core/apd.py", line 82, in extract_traffic_fatalities_page_details_link
    matches = regex.findall(news_page, re.MULTILINE)
              │     │       │          │  └ <RegexFlag.MULTILINE: 8>
              │     │       │          └ <module 're' from '/usr/local/lib/python3.7/re.py'>
              │     │       └ None
              │     └ <built-in method findall of re.Pattern object at 0x560df082c110>
              └ re.compile('<a href="(/news/traffic-fatality-\\d{1,3}-\\d|\\S*)">(Traffic Fatality #(\\d{1,3})).*\\s*</a>')

TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/home/circleci/project/tools/scrapd-merger.py", line 68, in <module>
    main()
  File "/home/circleci/project/tools/scrapd-merger.py", line 28, in main
    results = merge(json.loads(args.old.read()), json.loads(args.infile.read()))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exited with code 1
```

Expected Behavior
-----------------

ScrAPD should not fail like that.

Possible Solution
-----------------

* Implement a retry mechanism.

**Comment by rgreinho** [comment]
A very good article with ideas to solve the retry problem: http://allyouneedisbackend.com/blog/2017/09/15/how-backend-software-should-retry-on-failures/
